[versions]
spring-boot = "3.3.4"
spring-dependency-management = "1.1.6"

[libraries]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
